name: Shift Scheduling
description: The best app to integrate shift scheduling and availabilty tracking directly into Bullhorn!
version: 1.0
author: Bullhorn Superstars, llc
homepage: http://localhost:3000/home
support: http://localhost:3000/issues
readme: http://localhost:3000/readme.md
icon: https://placeholdit.imgix.net/~text?txtsize=12&txt=60x60&w=60&h=60
license: MIT
# For Client Specific Repos use corporation.id
private: false

keywords:
  - "Engage"
  - "Bullhorn2017"
  - "Shifts"

# Form Triggers
triggers:
  Candidate:
    - name: Crazy Validation One
      event: Edit
      url: http://localhost:3000/crazy-validator-one
    - name: Crazy Validation Two
      event: Add
      url: http://localhost:3000/crazy-validator-two

# Cards
cards:
  Candidate:
    - name: Availability
      url: http://localhost:3000/availability
      location: 0
    - name: Quick Match
      url: http://localhost:3000/matching-jobs
      location: 0
  JobOrder:
    - name: Shifts Needed
      url: http://localhost:3000/shifts
      location: 0
    - name: Quick Match
      url: http://localhost:3000/matching-candidates
      location: 0
      #enabled: false

# Tabs
tabs:
  Candidate:
    - name: Quick Match
      url: http://localhost:3000/automatch

# Menu Actions
# actions:
#   Candidate:
#     - name: Quick Match
#       url: http://localhost:3000/automatch
#       location: 2

# Pages
# pages:
#   - name: WhiteBoard
#     url: http://localhost:3000/automatch
#     hook: quick-match  

# Provisioning for Custom Objects
customObjects:
  Candidate:
    - name: Availability
      number: 1
      fields:
      - column: text1
        name: text1
        label: name
        type: Text
      - column: text2
        name: text2
        label: status
        type: Text
        options:
        - Maybe
        - Accepted
        - Rejected
      - column: date1
        name: date1
        label: DateOfEvent
        type: Date
  JobOrder:
    - name: Shifts
      number: 1
      fields:
      - column: text1
        name: text1
        label: name
        type: Text
      - column: text2
        name: text2
        label: status
        type: Text
        options:
        - Maybe
        - Accepted
        - Rejected
      - column: date1
        name: date1
        label: DateOfEvent
        type: Date

# FIELD MAPS
fieldMaps:
  JobSubmission:
    - name: customText5
      label: Date of Shift

# Private Label Attributes
privateLabelAttributes:
  candidateWorkflowIcons: "+[Custom:Shifts Needed|//localhost:3000/shiftneeds]"

  

# before_install:
#   - lets_validate_somehow

# after_install:
#   - send_notification
