name: Shift Scheduling
description: The best app to integrate shift scheduling and availabilty tracking directly into Bullhorn!
version: 1.0
author: Bullhorn Superstars, llc
homepage: https://engage-shifts.appspot.com/home
support: https://engage-shifts.appspot.com/issues
readme: https://engage-shifts.appspot.com/README.md
icon: https://engage-shifts.appspot.com/shift-calendar.png
license: MIT
# For Client Specific Repos use corporation.id
private: false

keywords:
  - "Engage"
  - "Bullhorn2017"
  - "Shifts"

# Form Triggers
triggers:
  Candidate:
    - name: Crazy Validation One
      event: Edit
      url: https://engage-shifts.appspot.com/crazy-validator-one
    - name: Crazy Validation Two
      event: Add
      url: https://engage-shifts.appspot.com/crazy-validator-two

# Cards
cards:
  Candidate:
    - name: Availability
      url: https://engage-shifts.appspot.com/availability
      location: 1
    - name: Quick Match
      url: https://engage-shifts.appspot.com/matching-jobs
      location: 1
  JobOrder:
    - name: Shifts Needed
      url: https://engage-shifts.appspot.com/shifts
      location: 1
    - name: Quick Match
      url: https://engage-shifts.appspot.com/matching-candidates
      location: 1
      #enabled: false

# Tabs
tabs:
  JobOrder:
    - name: Quick Match
      url: https://engage-shifts.appspot.com/automatch

# Menu Actions
# actions:
#   Candidate:
#     - name: Quick Match
#       url: https://engage-shifts.appspot.com/automatch
#       location: 2

# Pages
# pages:
#   - name: WhiteBoard
#     url: https://engage-shifts.appspot.com/automatch
#     hook: quick-match

# Provisioning for Custom Objects
customObjects:
  Candidate:
    - name: Availability
      label: Availability
      tabName: Availability
      displayType: Horizontal
      entityList: All
      number: 1
      fields:
      - column: text1
        name: text1
        label: name
        type: Text
      - column: text2
        name: text2
        label: status
        type: Text
        options:
        - Maybe
        - Accepted
        - Rejected
      - column: date1
        name: date1
        label: DateOfEvent
        type: Date
  JobOrder:
    - name: Shift
      label: Shift
      tabName: Shifts
      displayType: Horizontal
      entityList: All
      number: 1
      fields:
      - column: text1
        name: text1
        label: name
        type: Text
      - column: text2
        name: text2
        label: status
        type: Text
        options:
        - Maybe
        - Accepted
        - Rejected
      - column: date1
        name: date1
        label: DateOfEvent
        type: Date

# FIELD MAPS
fieldMaps:
  JobSubmission:
    - name: customText5
      label: Date of Shift

# Private Label Attributes
privateLabelAttributes:
  candidateWorkflowIcons: "+[Custom:Shifts Needed|//https://engage-shifts.appspot.com/shiftneeds]"

# before_install:
#   - lets_validate_somehow

# after_install:
#   - send_notification
